language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - libxt-dev
        - libogg-dev
        - libpng12-dev
        - libjpeg-dev
        - libvorbis-dev
        - libusb-dev
        - libglu1-mesa-dev
        - libx11-dev
        - libxrandr-dev
        - liblua50-dev
        - liblualib50-dev
        - libmad0-dev
        - libasound2-dev
        - libgtk2.0-dev
        - libavcodec-dev
        - libavformat-dev
        - libswscale-dev
        - libavutil-dev
        - libsamplerate0
        - libsndfile1
deploy:
  provider: releases
  api_key:
    secure: BALZxf88mPC8h/2XBED7A3Brui0qww1f5bUgZl6/x4/sCZPYDNw2LALdiy/a/tAjjPwTnQx1hyFK0vYNOeRPyMEtnR/kX6Z7OiJbhtz7pYNEAdlbnB70emjE5uB5Ol2XxDDC23g35ZqTJ+9icJhulHmkQT43Iy5X7511eWHqScIcxdi8p7wK/cclNq8iJa7BJhlBRqxfzIMhV2JnQejl7OX62dZGHqVYA0chLnhLMy6hp7Ll+alFpGRUNjqCN9f3E6QrJc6dK+fE+ZrFtafSfDvlqdsERMxxG50qGtOXhrblFrzQEjGEXJNFb/pqbq3B+FT/Y4/ZQhUGMv76OB9XCwIqSfwznuohGOo7h4W1jcNY4v0Alhx9J1v0Jo4bLLtzfbEUmdYWucthCZ2EiA0snsAjYAPodiibZVyMyKxjnckBEDCrXtMadExrf3E+s9Hpp1k98wb4pOaBgbSD46cju1z+8sCWXYfqAscoR1gxP6Qn2+roF0/xEjYNRzqEYnwr2KZELm47jnzOMcv9Z0uKUKxrg2qVVUBXqaxZlFZnUYZzacLg5wiNf8UQl0hEUojwfGBzusvpXVUiepjvZGKftpZeYkDnatwndXAsgU6zjVnvCxq4YmfEmF3DE36IDkbj46Y2GPlLq1WtwxL9Yrb3efLw2NKzP/nsH21tg1VJODc=
  file: openitg
  on:
    repo: kategray/openitg
