language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
              apt:
                  packages:
                      - libxt-dev
                      - libogg-dev
                      - libpng12-dev
                      - libjpeg-dev
                      - libvorbis-dev
                      - libusb-dev
                      - libglu1-mesa-dev
                      - libx11-dev
                      - libxrandr-dev 
                      - liblua50-dev 
                      - liblualib50-dev 
                      - libmad0-dev
                      - libasound2-dev
                      - libgtk2.0-dev
                      - libavcodec-dev
                      - libavformat-dev 
                      - libswscale-dev 
                      - libavutil-dev
